In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns   
import os
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import  StandardScaler , MinMaxScaler , LabelEncoder , OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_log_error , mean_absolute_error , mean_absolute_percentage_error , mean_squared_error
from sklearn.model_selection import train_test_split , RandomizedSearchCV , KFold , GridSearchCV

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import  RandomForestRegressor
from catboost import CatBoostRegressor
from xgboost import  XGBRegressor

from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer

In [ ]:
train = pd.read_csv('/kaggle/input/russian-car-plates-prices-prediction/train.csv')
test = pd.read_csv('/kaggle/input/russian-car-plates-prices-prediction/test.csv')

In [3]:
train.head()

   id      plate                 date   price
0   1  X059CP797  2024-12-26 00:00:00   65000
1   2  Y800MH790  2024-07-12 21:31:37  100000
2   3   A212TX77  2024-04-18 00:00:00  290000
3   4  P001AY199  2025-01-03 00:27:15  680000
4   5  P001AY199  2025-01-10 09:32:41  750000

In [4]:
test.head()

      id      plate                 date  price
0  51636  P700TT790  2025-01-27 00:00:00    NaN
1  51637  M081TX797  2025-02-10 00:00:00    NaN
2  51638  T333HX777  2025-02-11 00:00:00    NaN
3  51639  H744BH977  2025-02-03 00:00:00    NaN
4  51640  X066EM777  2025-02-12 00:00:00    NaN

In [5]:
print(f"training dataset shape = {train.shape}")
print("="*30)
print(f"test dataset shape = {test.shape}")

training dataset shape = (51635, 4)
==============================
test dataset shape = (7695, 4)

In [6]:
print(train.columns)
print("="*60)
print(test.columns)

Index(['id', 'plate', 'date', 'price'], dtype='object')
============================================================
Index(['id', 'plate', 'date', 'price'], dtype='object')

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51635 entries, 0 to 51634
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      51635 non-null  int64
 1   plate   51635 non-null  object
 2   date    51635 non-null  object
 3   price   51635 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.6+ MB

In [8]:
train.isnull().sum()

id       0
plate    0
date     0
price    0
dtype: int64

In [9]:
train.duplicated().sum()

np.int64(0)

In [10]:
train.describe()

                 id         price
count  51635.000000  5.163500e+04
mean   25818.000000  4.532253e+05
std    14905.884912  1.793287e+06
min        1.000000  2.000000e+04
25%    12909.500000  7.000000e+04
50%    25818.000000  1.500000e+05
75%    38726.500000  3.600000e+05
max    51635.000000  1.000000e+08

In [11]:
train.columns

Index(['id', 'plate', 'date', 'price'], dtype='object')

In [12]:
train["date"]

0        2024-12-26 00:00:00
1        2024-07-12 21:31:37
2        2024-04-18 00:00:00
3        2025-01-03 00:27:15
4        2025-01-10 09:32:41
                ...
51630    2025-01-29 00:00:00
51631    2025-01-31 00:00:00
51632    2025-02-06 00:00:00
51633    2024-04-24 11:30:07
51634    2023-10-06 00:00:00
Name: date, Length: 51635, dtype: object

In [13]:
train["plate"]

0        X059CP797
1        Y800MH790
2         A212TX77
3        P001AY199
4        P001AY199
           ...
51630    X023PP797
51631    M004KA161
51632    E888EB199
51633     X023XK77
51634    K450OC797
Name: plate, Length: 51635, dtype: object

# preprocessing for the training of the model

In [14]:
# provided in data 
REGION_CODES = {
    "Republic of Adygea": ["01"],
    "Altai Republic": ["04"],
    "Republic of Bashkortostan": ["02", "102", "702"],
    "Republic of Buryatia": ["03"],
    "Republic of Dagestan": ["05"],
    "Donetsk People's Republic": ["80", "180"],
    "Republic of Ingushetia": ["06"],
    "Kabardino-Balkarian Republic": ["07"],
    "Republic of Kalmykia": ["08"],
    "Karachay-Cherkess Republic": ["09"],
    "Republic of Karelia": ["10"],
    "Komi Republic": ["11"],
    "Republic of Crimea": ["82"],
    "Luhansk People's Republic": ["81", "181"],
    "Republic of Mari El": ["12"],
    "Republic of Mordovia": ["13", "113"],
    "Sakha Republic": ["14"],
    "Republic of North Ossetia": ["15"],
    "Republic of Tatarstan": ["16", "116", "716"],
    "Republic of Tyva (Tuva)": ["17"],
    "Udmurt Republic": ["18"],
    "Republic of Khakassia": ["19"],
    "Chechen Republic": ["20", "95"],
    "Chuvash Republic": ["21", "121"],
    "Altai Krai": ["22", "122"],
    "Zabaykalsky Krai": ["75"],
    "Kamchatka Krai": ["41"],
    "Krasnodar Krai": ["23", "93", "123", "193", "323"],
    "Krasnoyarsk Krai": ["24", "84", "88", "124"],
    "Perm Krai": ["59", "81", "159"],
    "Primorsky Krai": ["25", "125"],
    "Stavropol Krai": ["26", "126"],
    "Khabarovsk Krai": ["27"],
    "Amur Oblast": ["28"],
    "Arkhangelsk Oblast": ["29"],
    "Astrakhan Oblast": ["30", "130"],
    "Belgorod Oblast": ["31"],
    "Bryansk Oblast": ["32"],
    "Vladimir Oblast": ["33"],
    "Volgograd Oblast": ["34", "134"],
    "Vologda Oblast": ["35"],
    "Voronezh Oblast": ["36", "136"],
    "Zaporizhzhia Oblast": ["85", "185"],
    "Ivanovo Oblast": ["37"],
    "Irkutsk Oblast": ["38", "85", "138"],
    "Kaliningrad Oblast": ["39", "91"],
    "Kaluga Oblast": ["40"],
    "Kemerovo Oblast": ["42", "142"],
    "Kirov Oblast": ["43"],
    "Kostroma Oblast": ["44"],
    "Kurgan Oblast": ["45"],
    "Kursk Oblast": ["46"],
    "Leningrad Oblast": ["47", "147"],
    "Lipetsk Oblast": ["48"],
    "Magadan Oblast": ["49"],
    "Moscow Oblast": ["50", "90", "150", "190", "250", "550", "750", "790"],
    "Murmansk Oblast": ["51"],
    "Nizhny Novgorod Oblast": ["52", "152", "252"],
    "Novgorod Oblast": ["53"],
    "Novosibirsk Oblast": ["54", "154", "754"],
    "Omsk Oblast": ["55", "155"],
    "Orenburg Oblast": ["56", "156"],
    "Oryol Oblast": ["57"],
    "Penza Oblast": ["58", "158"],
    "Pskov Oblast": ["60"],
    "Rostov Oblast": ["61", "161", "761"],
    "Ryazan Oblast": ["62"],
    "Samara Oblast": ["63", "163", "763"],
    "Saratov Oblast": ["64", "164"],
    "Sakhalin Oblast": ["65"],
    "Sverdlovsk Oblast": ["66", "96", "196"],
    "Smolensk Oblast": ["67"],
    "Tambov Oblast": ["68"],
    "Tver Oblast": ["69"],
    "Tomsk Oblast": ["70"],
    "Tula Oblast": ["71"],
    "Tyumen Oblast": ["72", "172"],
    "Ulyanovsk Oblast": ["73", "173"],
    "Kherson Oblast": ["84", "184"],
    "Chelyabinsk Oblast": ["74", "174", "774"],
    "Yaroslavl Oblast": ["76"],
    "Moscow": ["77", "97", "99", "177", "197", "199", "777", "797", "799", "977"],
    "Saint Petersburg": ["78", "98", "178", "198"],
    "Sevastopol": ["92"],
    "Jewish Autonomous Oblast": ["79"],
    "Nenets Autonomous Okrug": ["83"],
    "Khanty-Mansi Autonomous Okrug": ["86", "186"],
    "Chukotka Autonomous Okrug": ["87"],
    "Yamalo-Nenets Autonomous Okrug": ["89"],
    "Baikonur": ["94"],
    "Occupational Administration of Kharkiv Oblast": ["188"],
}

# ((letters, numbers range (from, to), region code), is it forbidden to buy (bool), do they have an advantage on the road (bool), level of significance (author's opinion))
GOVERNMENT_CODES = {
    # Moscow
    ("AMP", (0, 999), "97"): ("Government of Russia", 1, 1, 10),
    ("AMP", (0, 999), "77"): ("Partially Government of Russia", 0, 1, 8),
    ("EKX", (0, 999), "77"): ("Partially Federal Protective Service (Federal Protective Service)", 0, 1, 6),
    ("EKX", (0, 999), "97"): ("Partially Federal Protective Service (Federal Protective Service)", 0, 1, 6),
    ("EKX", (0, 999), "99"): ("Partially Federal Protective Service (Federal Protective Service)", 0, 1, 6),
    ("KKX", (0, 999), "77"): ("Partially used on vehicles of Ministry of Security/Federal Counterintelligence Service /Federal Security Service of Russia", 0, 0, 1),
    ("CAC", (500, 999), "77"): ("Former officially 'open' plates of Ministry of Security/Federal Counterintelligence Service /Federal Security Service of Russia", 0, 0, 1),
    ("CAC", (500, 999), "77"): ("Former officially 'open' plates of Ministry of Security/Federal Counterintelligence Service /Federal Security Service of Russia", 0, 0, 1),
    ("AOO", (0, 999), "77"): ("Partially Presidential Administrative Directorate plates", 0, 1, 6),
    ("BOO", (0, 999), "77"): ("Partially Presidential Administrative Directorate plates", 0, 1, 6),
    ("MOO", (0, 999), "77"): ("Partially Presidential Administrative Directorate plates", 0, 1, 6),
    ("COO", (0, 999), "77"): ("Partially Administrative Directorate, Federation Council plates", 0, 1, 6),
    ("AMM", (0, 999), "99"): ("Partially plates of Moscow City Duma deputies, police", 0, 1, 4),
    ("CCC", (0, 999), "77"): ("Partially Central Special Communication, Courier Service, Ministry of Communications", 0, 1, 3),
    ("CCC", (0, 999), "99"): ("Partially Tax Police, Customs, Special Communications", 0, 1, 3),
    ("CCC", (0, 999), "97"): ("Partially Central Special Communication, Courier Service, Ministry of Communications", 0, 1, 3),
    ("KKK", (0, 999), "99"): ("Initially belonged to Courier Service, now used among private individuals", 0, 0, 1),
    ("OOO", (0, 999), "77"): ("Initially intended for Federal Security Service", 0, 0, 1),
    ("KMM", (0, 999), "77"): ("Partially Fire Department plates", 0, 1, 3),
    ("MMP", (300, 320), "77"): ("Partially Federal Security Service plates", 0, 1, 4),
    ("MMP", (0, 299), "77"): ("Partially Government of Russia, Federal Security Service, banks, and private individuals with connections in the traffic police", 0, 1, 2),
    ("MMP", (321, 999), "77"): ("Partially Government of Russia, Federal Security Service, banks, and private individuals with connections in the traffic police", 0, 1, 2),
    ("PMP", (0, 999), "77"): ("Partially Ministry of Justice plates", 0, 1, 3),
    ("AMO", (0, 999), "77"): ("Partially Moscow City Hall plates", 0, 1, 5),
    ("KOO", (0, 999), "77"): ("Partially Constitutional Court plates", 0, 1, 3),
    ("EPE", (0, 999), "77"): ("Partially State Duma plates", 0, 1, 3),
    ("AAA", (0, 999), "77"): ("Partially Administration of the President plates", 0, 1, 6),
    ("KMP", (0, 999), "77"): ("Partially Government of Russia plates", 0, 1, 3),
    ("TMP", (0, 999), "77"): ("Partially Government of Russia plates, as well as private individuals with connections in the traffic police", 0, 1, 2),
    ("YMP", (0, 999), "77"): ("Partially Government of Russia plates, as well as private individuals with connections in the traffic police", 0, 1, 2),
    ("XXX", (0, 999), "77"): ("Private individuals with connections in the traffic police", 0, 1, 2),
    ("YYY", (0, 999), "77"): ("Private individuals with connections in the traffic police", 0, 1, 2),
    ("XKX", (0, 999), "77"): ("Partially Federal Security Service and Federal Protective Service plates", 0, 1, 2),
    ("OMP", (0, 999), "77"): ("Partially Government of Russia, banks, and private individuals with connections in the traffic police", 0, 1, 2),
    ("EEE", (0, 999), "77"): ("Private individuals with connections in the traffic police", 0, 1, 2),

    # Moscow Oblast
    ("AMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("BMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("KMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("CMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("OMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("MMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("TMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("HMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("YMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("XMO", (0, 999), "50"): ("Partially various government agencies (administration, ambulance, traffic police, etc.)", 0, 1, 3),
    ("AMM", (0, 999), "50"): ("Partially plates of the regional administration", 0, 1, 5),
    ("AMM", (0, 999), "90"): ("Partially plates of the regional administration", 0, 1, 5),
    ("MMM", (0, 999), "50"): ("Partially plates of law enforcement in the region (prosecutor's office, EMERCOM, traffic police, etc.)", 0, 1, 5),
    ("MMM", (0, 999), "90"): ("Partially plates of law enforcement in the region (prosecutor's office, EMERCOM, traffic police, etc.)", 0, 1, 5),

    # Saint Petersburg
    ("OBO", (0, 999), "78"): ("Partially Departmental Security Service plates", 0, 1, 4),
    ("OBO", (0, 999), "98"): ("Partially Departmental Security Service plates", 0, 1, 4),
    ("OTT", (0, 999), "78"): ("Partially former traffic police plates (now replaced by 98)", 0, 0, 1),
    ("OTT", (0, 999), "98"): ("Partially traffic police plates", 0, 1, 4),
    ("OMM", (0, 999), "78"): ("Partially city district police plates", 0, 1, 3),
    ("OMM", (0, 999), "98"): ("Partially city district police plates", 0, 1, 3),
    ("OOM", (0, 999), "78"): ("Partially plates of the Main Department of Internal Affairs", 0, 1, 3),
    ("OOM", (0, 999), "98"): ("Partially plates of the Main Department of Internal Affairs", 0, 1, 3),
    ("OKO", (0, 100), "78"): ("Partially former plates of the prosecutor's office and judicial department (now replaced by 98)", 0, 0, 1),
    ("OKO", (0, 100), "98"): ("Partially plates of the prosecutor's office and judicial department", 0, 1, 3),
    ("OKO", (700, 999), "78"): ("Partially former Federal Security Service plates (now replaced by 98)", 0, 0, 1),
    ("OKO", (700, 999), "98"): ("Partially Federal Security Service plates", 0, 1, 3),
    ("OPP", (0, 999), "78"): ("Partially former plates of the Main Department of Internal Affairs (now replaced by 98)", 0, 0, 1),
    ("OPP", (0, 999), "98"): ("Partially plates of the Main Department of Internal Affairs", 0, 1, 3),
    ("OOH", (0, 999), "78"): ("Partially Federal Drug Control Service and Federal Tax Service plates", 0, 1, 3),
    ("OOH", (0, 999), "98"): ("Partially Federal Drug Control Service and Federal Tax Service plates", 0, 1, 3),
    ("OAO", (0, 999), "78"): ("Partially plates of the city and regional administration", 0, 1, 5),
    ("OAO", (0, 999), "98"): ("Partially plates of the city and regional administration", 0, 1, 5),
    ("AAA", (0, 100), "78"): ("Partially plates of the city and regional administration", 0, 1, 6),
    ("AAA", (0, 100), "98"): ("Partially plates of the city and regional administration", 0, 1, 6),
    ("OOO", (0, 899), "78"): ("Commercial plates", 0, 0, 2),
    ("OOO", (0, 899), "98"): ("Commercial plates", 0, 0, 2),
    ("OOO", (900, 999), "78"): ("Partially Federal Protective Service plates", 0, 1, 3),
    ("OOO", (900, 999), "98"): ("Partially Federal Protective Service plates", 0, 1, 3),
    ("OKC", (0, 999), "98"): ("Partially Constitutional Court of the Russian Federation plates", 0, 1, 3),
    ("OOC", (0, 999), "78"): ("Partially plates of heads of enterprises and organizations", 0, 0, 2),
    ("OOC", (0, 999), "98"): ("Partially plates of heads of enterprises and organizations", 0, 0, 2),
    ("MMM", (0, 999), "78"): ("Commercial plates", 0, 0, 2),
    ("MMM", (0, 999), "98"): ("Commercial plates", 0, 0, 2),

    # Altai Republic
    ("XXX", (0, 999), "04"): ("Widespread 'special' plates", 0, 0, 2),
    ("TTT", (0, 999), "04"): ("Rare 'special' plates", 0, 0, 2),
    ("PPP", (0, 999), "04"): ("Partially prosecutor's office of the republic", 0, 1, 3),
    ("PPA", (0, 999), "04"): ("Partially prosecutor's office of the republic", 0, 1, 3),
    ("MPA", (0, 999), "04"): ("Partially Ministry of Internal Affairs of the republic", 0, 1, 3),
    ("OOO", (0, 999), "04"): ("Partially plates of the government of the republic", 0, 1, 5),
    ("HHH", (0, 999), "04"): ("Partially the republic's tax service plates", 0, 1, 3),
    ("CCC", (0, 999), "04"): ("Partially plates belonging to the republic's judges", 0, 1, 3),

    # Republic of Bashkortostan
    ("PKC", (0, 999), "02"): ("Partially State Assembly (Kurultai) plates", 0, 1, 5),
    ("KKC", (0, 999), "02"): ("Partially State Assembly (Kurultai) plates", 0, 1, 5),
    ("OOO", (0, 999), "02"): ("Partially plates of leaders of large enterprises and ministries", 0, 1, 3),
    ("AAA", (0, 999), "02"): ("Partially plates of the republic's government", 0, 1, 5),

    # Republic of Karelia
    ("TTT", (0, 999), "10"): ("Partially government of the republic and Federal Security Service plates", 0, 1, 5),
    ("HHH", (0, 999), "10"): ("Partially plates of city and district administrations of the republic", 0, 1, 4),
    ("MMM", (0, 999), "10"): ("Partially plates of the Ministry of Internal Affairs of the republic", 0, 1, 3),
    ("EMP", (0, 999), "10"): ("Partially plates of the Ministry of Internal Affairs of the republic", 0, 1, 3),
    ("CCC", (0, 999), "10"): ("Partially plates of the prosecutor's office and judges' vehicles", 0, 1, 3),

    # Komi Republic
    ("TTT", (0, 999), "11"): ("Partially government of the republic and Federal Security Service plates", 0, 1, 5),
    ("OOO", (0, 999), "11"): ("Widespread semi-special plates, leaders of large industrial companies", 0, 1, 3),

    # Sakha Republic
    ("PPP", (0, 999), "14"): ("Partially plates of the republic's prosecutor's office", 0, 1, 3),
    ("AAA", (0, 999), "14"): ("Motor pool of the President, Government, Parliament of the republic, as well as heads of state enterprises", 0, 1, 5),

    # Republic of Tatarstan
    ("OAA", (0, 999), "16"): ("Partially plates of heads of district administrations", 0, 1, 5),
    ("OAA", (0, 999), "116"): ("Partially plates of heads of district administrations", 0, 1, 5),
    ("OAA", (0, 999), "716"): ("Partially plates of heads of district administrations", 0, 1, 5),

    # Krasnodar Krai
    ("PPP", (0, 999), "23"): ("Partially plates of the Krai and city administrations", 0, 1, 5),
    ("HHH", (0, 999), "23"): ("Partially plates of the tax authorities", 0, 1, 3),
    ("OOO", (0, 999), "23"): ("Partially plates of the Krai and city administrations", 0, 1, 5),
    ("KKK", (0, 999), "23"): ("Partially plates of the Krai administration", 0, 1, 5),

    # Krasnoyarsk Krai
    ("KPK", (0, 999), "24"): ("Partially plates of the Krai administration", 0, 1, 5),
    ("OOO", (0, 999), "24"): ("Partially Federal Security Service plates of the Krai", 0, 1, 3),
    ("MKK", (0, 999), "24"): ("Partially former plates of the Ministry of Internal Affairs of the Krai", 0, 0, 1),

    # Primorsky Krai
    ("BOO", (0, 999), "25"): ("Partially military plates", 0, 1, 3),
    ("BOO", (0, 999), "125"): ("Partially city services plates in Vladivostok and districts", 0, 1, 2),
    ("AAA", (0, 999), "25"): ("Issued first in Vladivostok", 0, 0, 2),
    ("AAA", (0, 999), "125"): ("One of the most 'special' series, prosecutor's office", 1, 1, 5),
    ("HHH", (0, 999), "25"): ("Partially plates of the administration and vehicles of City Duma deputies", 0, 1, 3),
    ("MMM", (0, 999), "25"): ("Partially plates of the deputies of the Krai Legislative Assembly", 0, 1, 3),
    ("CCC", (0, 999), "25"): ("Partially plates of the Krai administration", 0, 1, 5),
    ("XXX", (0, 999), "25"): ("Partially plates of the prosecutor's office and the Department of Internal Affairs", 0, 1, 2),
    ("OOO", (0, 999), "25"): ("Partially former plates of the Krai administration (during Governor Evgeny Nazdratenko)", 0, 0, 1),
    ("TTT", (0, 999), "25"): ("Partially former plates of the Vladivostok administration and federal agencies in the Krai (during Mayor Yuri Kopylov)", 0, 0, 1),
    ("MBK", (0, 999), "25"): ("Partially plates for employees of the Department of Internal Affairs", 0, 1, 3),
    ("MBK", (0, 999), "125"): ("Partially plates for employees of the Department of Internal Affairs", 0, 1, 3),
    ("MOO", (0, 999), "25"): ("Partially plates for Krai agencies of the Department of Internal Affairs, EMERCOM, firefighters, etc.", 0, 1, 2),
    ("MOO", (0, 999), "125"): ("Partially plates for Krai agencies of the Department of Internal Affairs, EMERCOM, firefighters, etc.", 0, 1, 2),
    ("HOO", (0, 999), "25"): ("Partially plates of the Department of Internal Affairs, traffic police in the southeastern region of the Krai (Nakhodka)", 0, 1, 3),
    ("HOO", (0, 999), "125"): ("Partially plates of the Department of Internal Affairs, traffic police in the southeastern region of the Krai (Nakhodka)", 0, 1, 3),
    ("YOO", (0, 999), "25"): ("Partially plates of the Department of Internal Affairs, traffic police in the central region of the Krai (Ussuriysk)", 0, 1, 3),
    ("YOO", (0, 999), "125"): ("Partially plates of the Department of Internal Affairs, traffic police in the central region of the Krai (Ussuriysk)", 0, 1, 3),
    ("COO", (0, 999), "25"): ("Partially plates of the Department of Internal Affairs, traffic police in the northern region of the Krai (Spassk-Dalny)", 0, 1, 3),
    ("COO", (0, 999), "125"): ("Partially plates of the Department of Internal Affairs, traffic police in the northern region of the Krai (Spassk-Dalny)", 0, 1, 3),

    # Vologda Oblast
    ("AAA", (0, 999), "35"): ("Partially plates of the regional government and Vologda city administration", 0, 1, 5),

    # Volgograd Oblast
    ("AAM", (0, 999), "34"): ("Partially plates of the Oblast Duma", 0, 1, 3),
    ("PAA", (0, 999), "34"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("AAA", (0, 999), "34"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),
    ("ACK", (0, 999), "34"): ("Partially plates of the Investigative Committee, Main Department of Internal Affairs", 0, 1, 3),
    ("YYY", (0, 999), "34"): ("Partially Federal Security Service plates", 0, 1, 3),
    ("AAK", (0, 999), "34"): ("Partially plates of the Federal Bailiff Service, Ministry of Justice, and Judicial Department", 0, 1, 3),

    # Voronezh Oblast
    ("ААА", (0, 999), "36"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("BOA", (0, 999), "36"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("MMM", (0, 999), "36"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),

    # Kaliningrad Oblast
    ("AAK", (0, 999), "39"): ("Partially plates of the Oblast Administration, Federal Security Service, and Prosecutor's Office", 0, 1, 5),
    ("KKK", (0, 999), "39"): ("Partially plates of the Oblast Administration, Federal Security Service, and Prosecutor's Office", 0, 1, 5),
    ("PPP", (0, 999), "39"): ("Partially former plates of the Oblast Administration (during Governor Boos)", 0, 0, 1),

    # Kaluga Oblast
    ("OOO", (0, 999), "40"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("TTT", (0, 999), "40"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("PPP", (0, 999), "40"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),

    # Kurgan Oblast
    ("OOO", (0, 999), "45"): ("Partially former plates of the Oblast Administration", 0, 0, 1),
    ("TTT", (0, 999), "45"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("OKO", (0, 999), "45"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),

    # Novosibirsk Oblast
    ("AAA", (0, 199), "54"): ("Plates for Presidential Plenipotentiaries", 1, 1, 7),
    ("AAA", (200, 999), "54"): ("'Special' plates", 0, 1, 4),
    ("HHH", (0, 999), "54"): ("Partially plates of the Novosibirsk mayor's office, Oblast Administration, and Oblast Council", 0, 1, 5),
    ("ACK", (0, 999), "54"): ("Partially Federal Security Service plates of the Oblast", 0, 1, 3),
    ("AHO", (0, 999), "54"): ("Partially former plates of the Oblast Administration", 0, 0, 1),
    ("AAO", (0, 999), "54"): ("Partially plates of various government agencies, including district administrations of Novosibirsk", 0, 1, 3),
    ("PPP", (0, 999), "54"): ("'Morozov' plates (introduced by former head of traffic police Pyotr Morozov)", 0, 1, 2),
    ("MOP", (0, 999), "54"): ("'Morozov' plates (introduced by former head of traffic police Pyotr Morozov)", 0, 1, 2),

    # Oryol Oblast
    ("AAA", (0, 999), "57"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("AOO", (0, 999), "57"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("OAO", (0, 999), "57"): ("Partially plates of directors of public joint-stock companies", 0, 1, 2),

    # Rostov Oblast
    ("APO", (0, 999), "61"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("AAA", (0, 999), "61"): ("Partially plates of district heads of Rostov-on-Don, mayors of Oblast cities", 0, 1, 5),
    ("APY", (0, 999), "61"): ("Partially plates of the Rostov-on-Don administration", 0, 1, 5),
    ("KKK", (0, 999), "61"): ("Partially former plates for Presidential Plenipotentiaries (during Viktor Kazantsev)", 0, 0, 1),
    ("HHH", (0, 999), "61"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),
    ("MMM", (0, 999), "61"): ("Partially plates of the Oblast Department of Internal Affairs", 0, 1, 3),
    ("OOO", (0, 999), "61"): ("Partially plates of the Oblast Legislative Assembly", 0, 1, 4),
    ("BBK", (0, 999), "61"): ("Partially plates of insurance companies in Rostov-on-Don", 0, 1, 1),

    # Saratov Oblast
    ("AAA", (0, 999), "164"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("PPP", (0, 999), "164"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("XXX", (0, 999), "64"): ("Partially plates of the Oblast courts", 0, 1, 3),
    ("MMM", (0, 999), "64"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),
    ("OAA", (0, 999), "64"): ("Partially Federal Security Service plates of the Oblast", 0, 1, 3),

    # Tomsk Oblast
    ("ATO", (0, 999), "70"): ("Partially plates of the Oblast Administration", 0, 1, 5),

    # Tyumen Oblast
    ("ATO", (0, 999), "72"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("PTO", (0, 999), "72"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("MTO", (0, 999), "72"): ("Partially plates of the Oblast Prosecutor's Office", 0, 1, 3),
    ("HTO", (0, 999), "72"): ("Partially plates of the Tax Service", 0, 1, 3),
    ("CTO", (0, 999), "72"): ("Partially plates of the Oblast courts", 0, 1, 3),
    ("YTO", (0, 999), "72"): ("Partially plates of the bailiff service", 0, 1, 3),
    ("BAA", (0, 999), "72"): ("Partially plates of the Oblast Ministry of Internal Affairs", 0, 1, 3),
    ("KKK", (0, 999), "72"): ("'Gangster' plates", 0, 1, 1),

    # Arkhangelsk Oblast
    ("TTT", (0, 999), "29"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("PPP", (0, 999), "29"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("MAO", (0, 999), "29"): ("Partially plates of the Oblast Ministry of Internal Affairs", 0, 1, 3),

    # Ryazan Oblast
    ("APO", (0, 999), "62"): ("Partially plates of the Oblast Administration", 0, 1, 5),

    # Samara Oblast
    ("PAA", (0, 999), "63"): ("Partially plates of the Oblast Administration", 0, 1, 5),
    ("AAP", (0, 999), "63"): ("Partially plates of the Oblast Administration", 0, 1, 5),
}

In [15]:
def get_region_code(plate):
    region_code = plate[6:]
    for region , code in REGION_CODES.items():
        if region_code in code:
            return region
    return "UNKNOWN REGION"


get_region_code("A123BC36")  # Example usage, should return "Voronezh Oblast"

'Voronezh Oblast'

In [16]:
def preprocessing_data(train):
    train["date"] = pd.to_datetime(train["date"] , errors='coerce')
    train["year"] = train["date"].dt.year.astype("int64")
    train["month"] = train["date"].dt.month.astype("int64")
    train["day"] = train["date"].dt.day.astype("int64")
    train["day_of_week"] =train["date"].dt.dayofweek.astype("int64")
    train["week_of_year"] = train["date"].dt.isocalendar().week
    train["is_weekend"] = train["day_of_week"].isin([5, 6]).astype('int64')  
    train["is_start_of_month"] = (train["day"] == 1).astype('int64')
    train["plate_number"] = train["plate"].apply(lambda x : x[1:4]).astype("str")
    train["plate_series"] = train["plate"].apply(lambda x : x[0] + x[4:6]).astype("str")
    train['region'] = train['plate'].str.extract(r"(\d{2,3})$")[0].astype(str) # consider last 2-3 digits
    train = train.sort_values(by=['region', 'date'])
    train['price'] = np.log1p(train['price'])
    train['is_palindrome_letters'] = train['plate_series'].apply(lambda x: x == x[::-1])
    train['is_palindrome_numbers'] = train['plate_number'].apply(lambda x: x == x[::-1])
    train['unique_letters_count'] = train['plate_series'].apply(lambda x: len(set(x)))
    train['unique_numbers_count'] = train['plate_number'].apply(lambda x: len(set(x)))
    train["has_repeating_digits"] = train["plate_number"].apply(lambda x: len(set(x)) < len(x))
    digits = train['plate_number'].apply(lambda s: list(map(int, s)))
    train[['d1', 'd2', 'd3']] = pd.DataFrame(digits.tolist(), index=train.index)
    train['sum_numbers'] = train['d1'] + train['d2'] + train['d3']
    train['product_numbers'] = train['d1'] * train['d2'] * train['d3']
    train = train.drop(columns=['id', 'plate', 'date', 'd1', 'd2', 'd3', 'sum_numbers'])
    
    return train


def feature_engineering(df):
    le = LabelEncoder()
    col = ['region', 'is_palindrome_letters', 'is_palindrome_numbers', 'has_repeating_digits', 'plate_number', 'plate_series']
    df = df.apply(lambda x: le.fit_transform(x) if x.name in col else x, axis=0)
    return df

df = preprocessing_data(train)
df = feature_engineering(df)

df

,price,year,month,day,day_of_week,week_of_year,is_weekend,is_start_of_month,plate_number,plate_series,region,is_palindrome_letters,is_palindrome_numbers,unique_letters_count,unique_numbers_count,has_repeating_digits,product_numbers
3955,11.156265,2022,2,10,3,6,0,0,109,469,0,0,0,2,2,1,0
45862,15.894952,2022,2,15,1,7,0,0,643,78,0,0,0,2,2,1,96
27705,11.289794,2022,3,9,2,10,0,0,382,1087,0,1,1,2,2,1,72
1123,11.512935,2022,3,24,3,12,0,0,10,1027,0,1,0,2,2,1,0
16250,12.206078,2022,3,24,3,12,0,0,76,1613,0,0,0,3,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47880,14.220976,2025,2,12,2,7,0,0,776,1247,144,0,1,3,1,1,343
48527,14.827112,2025,2,12,2,7,0,0,4,1004,144,0,0,3,2,1,0
49334,12.611541,2025,2,12,2,7,0,0,79,520,144,0,1,3,2,1,0
50217,13.279369,2025,2,12,2,7,0,0,89,1453,144,0,1,2,2,1,0
50467,13.883170,2025,2,12,2,7,0,0,0,487,144,0,0,3,2,1,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51635 entries, 3955 to 50467
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   price                  51635 non-null  float64
 1   year                   51635 non-null  int64
 2   month                  51635 non-null  int64
 3   day                    51635 non-null  int64
 4   day_of_week            51635 non-null  int64
 5   week_of_year           51635 non-null  UInt32
 6   is_weekend             51635 non-null  int64
 7   is_start_of_month      51635 non-null  int64
 8   plate_number           51635 non-null  int64
 9   plate_series           51635 non-null  int64
 10  region                 51635 non-null  int64
 11  is_palindrome_letters  51635 non-null  int64
 12  is_palindrome_numbers  51635 non-null  int64
 13  unique_letters_count   51635 non-null  int64
 14  unique_numbers_count   51635 non-null  int64
 15  has_repeating_digits   51635 non-null  int64
 16  product_numbers        51635 non-null  int64
dtypes: UInt32(1), float64(1), int64(15)
memory usage: 6.9 MB

## pipeline and model creation

In [18]:
param_grids = {
    'DecisionTree': {
        'model__max_depth': [3, 5, 10, None],
        'model__min_samples_split': [2, 5, 10],
    },
    'RandomForest': {
        'model__n_estimators': [100, 200],
        'model__max_depth': [5, 10, None],
        'model__min_samples_split': [2, 5],
    },
    'CatBoost': {
        'model__iterations': [100, 200],
        'model__depth': [4, 6, 8],
        'model__learning_rate': [0.01, 0.1],
    },
    'XGBoost': {
        'model__n_estimators': [100, 200],
        'model__max_depth': [3, 5, 7],
        'model__learning_rate': [0.01, 0.1],
    }
}

In [19]:
pipelines = {
    'DecisionTree': Pipeline([
        ('scaler', MinMaxScaler()),
        ('model', DecisionTreeRegressor())
    ]),
    'RandomForest': Pipeline([
        ('scaler', MinMaxScaler()),
        ('model', RandomForestRegressor())
    ]),
    'CatBoost': Pipeline([
        ('scaler', MinMaxScaler()),
        ('model', CatBoostRegressor())
    ]),
    'XGBoost': Pipeline([
        ('scaler', MinMaxScaler()),
        ('model', XGBRegressor())
    ])
}

In [20]:
# SMAPE function
def smape_(y_true, y_pred):
    denominator = (np.abs(y_true) + np.abs(y_pred)) / 2
    diff = np.abs(y_true - y_pred) / denominator
    diff[denominator == 0] = 0  # avoid division by zero
    return np.mean(diff) * 100

# Sklearn scorer for RandomizedSearchCV
smape_scorer = make_scorer(smape_, greater_is_better=False)

In [21]:
df.columns

Index(['price', 'year', 'month', 'day', 'day_of_week', 'week_of_year',
       'is_weekend', 'is_start_of_month', 'plate_number', 'plate_series',
       'region', 'is_palindrome_letters', 'is_palindrome_numbers',
       'unique_letters_count', 'unique_numbers_count', 'has_repeating_digits',
       'product_numbers'],
      dtype='object')

In [22]:
X = df.drop(columns=['price'])
y = df['price'] # very large values, so we use log transformation

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [25]:
results = []
for name in pipelines:
    print(f"\n🔍 Training {name} with RandomizedSearchCV...")
    
    search = RandomizedSearchCV(
        pipelines[name],
        param_distributions=param_grids[name],
        n_iter=5,
        scoring=smape_scorer,  # use scorer object here
        cv=5,
        random_state=42,
        n_jobs=-1
    )
    
    search.fit(X_train, y_train)
    y_pred = search.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    smape_score = smape_(y_test, y_pred)  # call the actual function here
    
    print(f"✅ Best Params for {name}:")
    print(search.best_params_)
    
    print(f"📉 MSE: {mse:.4f}")
    print(f"📉 MAE: {mae:.4f}")
    print(f"📉 SMAPE: {smape_score:.2f}%")
    
    results.append({
        'Model': name,
        'Best Params': search.best_params_,
        'MSE': mse,
        'MAE': mae,
        'SMAPE': smape_score
    })

🔍 Training DecisionTree with RandomizedSearchCV...
✅ Best Params for DecisionTree:
{'model__min_samples_split': 10, 'model__max_depth': 10}
📉 MSE: 0.5398
📉 MAE: 0.5255
📉 SMAPE: 4.32%

🔍 Training RandomForest with RandomizedSearchCV...
✅ Best Params for RandomForest:
{'model__n_estimators': 200, 'model__min_samples_split': 2, 'model__max_depth': None}
📉 MSE: 0.4391
📉 MAE: 0.4576
📉 SMAPE: 3.77%

🔍 Training CatBoost with RandomizedSearchCV...
0:	learn: 1.1038894	total: 52.8ms	remaining: 5.23s
0:	learn: 1.1528749	total: 56.7ms	remaining: 11.3s
1:	learn: 1.1474188	total: 61.7ms	remaining: 6.11s
2:	learn: 1.1421047	total: 66.5ms	remaining: 4.37s
1:	learn: 1.0576677	total: 72.2ms	remaining: 3.54s
3:	learn: 1.1368530	total: 89.3ms	remaining: 4.37s
0:	learn: 1.1524658	total: 77.9ms	remaining: 15.5s
2:	learn: 1.0181615	total: 109ms	remaining: 3.51s
0:	learn: 1.1493717	total: 101ms	remaining: 20.2s
1:	learn: 1.1470554	total: 113ms	remaining: 11.2s
4:	learn: 1.1321461	total: 136ms	remaining: 5.3s
0:	learn: 1.1544018	total: 103ms	remaining: 20.4s
0:	learn: 1.1013199	total: 127ms	remaining: 12.6s
0:	learn: 1.1029548	total: 109ms	remaining: 10.8s
3:	learn: 0.9843899	total: 151ms	remaining: 3.63s
0:	learn: 1.1506403	total: 123ms	remaining: 24.5s
2:	learn: 1.1417405	total: 154ms	remaining: 10.1s
4:	learn: 0.9572948	total: 190ms	remaining: 3.61s
1:	learn: 1.1489563	total: 156ms	remaining: 15.4s
1:	learn: 1.1452156	total: 168ms	remaining: 16.6s
5:	learn: 1.1270265	total: 196ms	remaining: 6.34s
1:	learn: 1.0568028	total: 164ms	remaining: 8.05s
1:	learn: 1.1439675	total: 190ms	remaining: 18.8s
2:	learn: 1.1399611	total: 195ms	remaining: 12.8s
3:	learn: 1.1368631	total: 203ms	remaining: 9.93s
1:	learn: 1.0553133	total: 214ms	remaining: 10.5s
6:	learn: 1.1225470	total: 237ms	remaining: 6.53s
2:	learn: 1.1436611	total: 211ms	remaining: 13.8s
4:	learn: 1.1323954	total: 233ms	remaining: 9.09s
5:	learn: 0.9319861	total: 274ms	remaining: 4.3s
2:	learn: 1.1386957	total: 252ms	remaining: 16.6s
2:	learn: 1.0185679	total: 243ms	remaining: 7.86s
3:	learn: 1.1348307	total: 257ms	remaining: 12.6s
7:	learn: 1.1178240	total: 287ms	remaining: 6.89s
5:	learn: 1.1272577	total: 276ms	remaining: 8.91s
6:	learn: 0.9102316	total: 309ms	remaining: 4.1s
2:	learn: 1.0173077	total: 294ms	remaining: 9.52s
8:	learn: 1.1128498	total: 305ms	remaining: 6.47s
3:	learn: 1.1384299	total: 274ms	remaining: 13.4s
4:	learn: 1.1338655	total: 288ms	remaining: 11.2s
4:	learn: 1.1303312	total: 310ms	remaining: 12.1s
5:	learn: 1.1287593	total: 302ms	remaining: 9.76s
7:	learn: 0.8913948	total: 341ms	remaining: 3.92s
6:	learn: 1.1227053	total: 319ms	remaining: 8.79s
6:	learn: 1.1242140	total: 317ms	remaining: 8.74s
3:	learn: 1.1335557	total: 337ms	remaining: 16.5s
9:	learn: 1.1081682	total: 360ms	remaining: 6.84s
7:	learn: 1.1195605	total: 331ms	remaining: 7.94s
3:	learn: 0.9837202	total: 357ms	remaining: 8.56s
3:	learn: 0.9851431	total: 335ms	remaining: 8.04s
7:	learn: 1.1178796	total: 357ms	remaining: 8.57s
8:	learn: 1.1147149	total: 345ms	remaining: 7.33s
5:	learn: 1.1253035	total: 357ms	remaining: 11.5s
9:	learn: 1.1101405	total: 359ms	remaining: 6.82s
8:	learn: 1.1129680	total: 376ms	remaining: 7.99s
9:	learn: 1.1083611	total: 393ms	remaining: 7.46s
10:	learn: 1.1035469	total: 418ms	remaining: 7.18s
10:	learn: 1.1037129	total: 405ms	remaining: 6.96s
6:	learn: 1.1207336	total: 402ms	remaining: 11.1s
4:	learn: 1.1291219	total: 410ms	remaining: 16s
11:	learn: 1.0991168	total: 418ms	remaining: 6.54s
8:	learn: 0.8731671	total: 442ms	remaining: 4.47s
4:	learn: 0.9589209	total: 406ms	remaining: 7.72s
12:	learn: 1.0944077	total: 432ms	remaining: 6.21s
4:	learn: 0.9566407	total: 461ms	remaining: 8.76s
11:	learn: 1.0991979	total: 470ms	remaining: 7.37s
13:	learn: 1.0899136	total: 454ms	remaining: 6.04s
7:	learn: 1.1160038	total: 460ms	remaining: 11s
5:	learn: 1.1240394	total: 472ms	remaining: 15.3s
14:	learn: 1.0857777	total: 478ms	remaining: 5.89s
5:	learn: 0.9335306	total: 465ms	remaining: 7.28s
9:	learn: 0.8581270	total: 512ms	remaining: 4.61s
8:	learn: 1.1112435	total: 485ms	remaining: 10.3s
12:	learn: 1.0946560	total: 519ms	remaining: 7.46s
15:	learn: 1.0812192	total: 526ms	remaining: 6.04s
9:	learn: 1.1067296	total: 526ms	remaining: 10s
10:	learn: 1.1055174	total: 518ms	remaining: 8.91s
6:	learn: 0.9118003	total: 519ms	remaining: 6.9s
6:	learn: 1.1194515	total: 537ms	remaining: 14.8s
10:	learn: 0.8459704	total: 573ms	remaining: 4.64s
16:	learn: 1.0767719	total: 555ms	remaining: 5.97s
10:	learn: 1.1021651	total: 554ms	remaining: 9.51s
5:	learn: 0.9309896	total: 571ms	remaining: 8.94s
13:	learn: 1.0902847	total: 580ms	remaining: 7.7s
7:	learn: 0.8942571	total: 548ms	remaining: 6.3s
17:	learn: 1.0726705	total: 569ms	remaining: 5.75s
11:	learn: 1.0975197	total: 591ms	remaining: 9.26s
11:	learn: 1.1011930	total: 586ms	remaining: 9.18s
11:	learn: 0.8353092	total: 626ms	remaining: 4.59s
8:	learn: 0.8762250	total: 587ms	remaining: 5.94s
7:	learn: 1.1147728	total: 602ms	remaining: 14.4s
18:	learn: 1.0688307	total: 612ms	remaining: 5.83s
14:	learn: 1.0860256	total: 641ms	remaining: 7.9s
9:	learn: 0.8618155	total: 619ms	remaining: 5.57s
19:	learn: 1.0645936	total: 635ms	remaining: 5.71s
6:	learn: 0.9098374	total: 650ms	remaining: 8.64s
12:	learn: 1.0929139	total: 638ms	remaining: 9.18s
20:	learn: 1.0604603	total: 649ms	remaining: 5.54s
10:	learn: 0.8489751	total: 636ms	remaining: 5.15s
21:	learn: 1.0563267	total: 663ms	remaining: 5.37s
12:	learn: 1.0965605	total: 657ms	remaining: 9.44s
11:	learn: 0.8387101	total: 658ms	remaining: 4.82s
12:	learn: 0.8256882	total: 699ms	remaining: 4.68s
22:	learn: 1.0526133	total: 677ms	remaining: 5.21s
8:	learn: 1.1100321	total: 676ms	remaining: 14.3s
23:	learn: 1.0488140	total: 690ms	remaining: 5.06s
12:	learn: 0.8289395	total: 679ms	remaining: 4.55s
13:	learn: 1.0886055	total: 697ms	remaining: 9.27s
24:	learn: 1.0449477	total: 703ms	remaining: 4.92s
15:	learn: 1.0817487	total: 724ms	remaining: 8.33s
7:	learn: 0.8914505	total: 727ms	remaining: 8.36s
25:	learn: 1.0413419	total: 717ms	remaining: 4.8s
13:	learn: 0.8208966	total: 710ms	remaining: 4.36s
13:	learn: 0.8166489	total: 754ms	remaining: 4.63s
13:	learn: 1.0920630	total: 720ms	remaining: 9.56s
14:	learn: 0.8135097	total: 735ms	remaining: 4.17s
16:	learn: 1.0776623	total: 770ms	remaining: 8.29s
9:	learn: 1.1054809	total: 753ms	remaining: 14.3s
14:	learn: 1.0844092	total: 756ms	remaining: 9.32s
15:	learn: 0.8066916	total: 753ms	remaining: 3.95s
16:	learn: 0.7999667	total: 774ms	remaining: 3.78s
8:	learn: 0.8755442	total: 801ms	remaining: 8.1s
14:	learn: 0.8090802	total: 815ms	remaining: 4.62s
14:	learn: 1.0878604	total: 778ms	remaining: 9.59s
17:	learn: 1.0735344	total: 827ms	remaining: 8.36s
10:	learn: 1.1006852	total: 816ms	remaining: 14s
17:	learn: 0.7926110	total: 804ms	remaining: 3.66s
15:	learn: 0.8023190	total: 845ms	remaining: 4.43s
15:	learn: 1.0801438	total: 833ms	remaining: 9.57s
18:	learn: 0.7878783	total: 826ms	remaining: 3.52s
16:	learn: 0.7947504	total: 885ms	remaining: 4.32s
19:	learn: 0.7831616	total: 856ms	remaining: 3.42s
17:	learn: 0.7903319	total: 907ms	remaining: 4.13s
18:	learn: 1.0696152	total: 904ms	remaining: 8.61s
9:	learn: 0.8599930	total: 888ms	remaining: 7.99s
16:	learn: 1.0757575	total: 884ms	remaining: 9.52s
15:	learn: 1.0836045	total: 877ms	remaining: 10.1s
18:	learn: 0.7850621	total: 925ms	remaining: 3.94s
26:	learn: 1.0374896	total: 903ms	remaining: 5.79s
20:	learn: 0.7791614	total: 895ms	remaining: 3.37s
11:	learn: 1.0962950	total: 909ms	remaining: 14.2s
19:	learn: 0.7794546	total: 946ms	remaining: 3.79s
20:	learn: 0.7757505	total: 966ms	remaining: 3.63s
16:	learn: 1.0795367	total: 931ms	remaining: 10s
21:	learn: 0.7757393	total: 934ms	remaining: 3.31s
17:	learn: 1.0716692	total: 939ms	remaining: 9.5s
27:	learn: 1.0336548	total: 962ms	remaining: 5.91s
21:	learn: 0.7708656	total: 986ms	remaining: 3.5s
10:	learn: 0.8471785	total: 964ms	remaining: 7.8s
28:	learn: 1.0299512	total: 976ms	remaining: 5.76s
12:	learn: 1.0916953	total: 974ms	remaining: 14s
22:	learn: 0.7676012	total: 1s	remaining: 3.35s
19:	learn: 1.0656114	total: 998ms	remaining: 8.98s
29:	learn: 1.0264716	total: 989ms	remaining: 5.61s
23:	learn: 0.7645068	total: 1.01s	remaining: 3.21s
22:	learn: 0.7716735	total: 980ms	remaining: 3.28s
11:	learn: 0.8374089	total: 999ms	remaining: 7.32s
30:	learn: 1.0228754	total: 1s	remaining: 5.47s
23:	learn: 0.7688155	total: 1.01s	remaining: 3.2s
24:	learn: 0.7605509	total: 1.05s	remaining: 3.15s
18:	learn: 1.0674866	total: 1.02s	remaining: 9.74s
25:	learn: 0.7573345	total: 1.07s	remaining: 3.04s
17:	learn: 1.0754040	total: 1.02s	remaining: 10.4s
24:	learn: 0.7654682	total: 1.04s	remaining: 3.13s
13:	learn: 1.0871379	total: 1.06s	remaining: 14.1s
12:	learn: 0.8271710	total: 1.06s	remaining: 7.11s
26:	learn: 0.7544471	total: 1.09s	remaining: 2.95s
27:	learn: 0.7519258	total: 1.11s	remaining: 2.85s
20:	learn: 1.0615551	total: 1.11s	remaining: 9.43s
28:	learn: 0.7487612	total: 1.13s	remaining: 2.75s
25:	learn: 0.7615513	total: 1.1s	remaining: 3.13s
29:	learn: 0.7463640	total: 1.13s	remaining: 2.65s
18:	learn: 1.0714648	total: 1.09s	remaining: 10.4s
30:	learn: 0.7442169	total: 1.15s	remaining: 2.56s
19:	learn: 1.0633399	total: 1.11s	remaining: 10s
13:	learn: 0.8179518	total: 1.13s	remaining: 6.95s
14:	learn: 1.0829304	total: 1.13s	remaining: 14s
31:	learn: 0.7420681	total: 1.17s	remaining: 2.48s
26:	learn: 0.7590733	total: 1.15s	remaining: 3.12s
32:	learn: 0.7392995	total: 1.19s	remaining: 2.42s
31:	learn: 1.0196141	total: 1.17s	remaining: 6.17s
33:	learn: 0.7373390	total: 1.2s	remaining: 2.34s
20:	learn: 1.0592447	total: 1.18s	remaining: 10s
21:	learn: 1.0574965	total: 1.21s	remaining: 9.75s
34:	learn: 0.7359475	total: 1.22s	remaining: 2.26s
14:	learn: 0.8108451	total: 1.2s	remaining: 6.78s
19:	learn: 1.0672995	total: 1.19s	remaining: 10.7s
35:	learn: 0.7341439	total: 1.23s	remaining: 2.19s
15:	learn: 1.0786940	total: 1.21s	remaining: 13.9s
27:	learn: 0.7567012	total: 1.21s	remaining: 3.1s
36:	learn: 0.7327820	total: 1.24s	remaining: 2.12s
37:	learn: 0.7313474	total: 1.26s	remaining: 2.05s
38:	learn: 0.7295781	total: 1.27s	remaining: 1.99s
22:	learn: 1.0536795	total: 1.27s	remaining: 9.77s
20:	learn: 1.0633675	total: 1.23s	remaining: 10.5s
32:	learn: 1.0160280	total: 1.26s	remaining: 6.36s
39:	learn: 0.7274662	total: 1.28s	remaining: 1.93s
21:	learn: 1.0551508	total: 1.25s	remaining: 10.2s
40:	learn: 0.7258608	total: 1.3s	remaining: 1.86s
15:	learn: 0.8041647	total: 1.27s	remaining: 6.66s
16:	learn: 1.0745920	total: 1.27s	remaining: 13.7s
41:	learn: 0.7241719	total: 1.3s	remaining: 1.8s
28:	learn: 0.7529974	total: 1.28s	remaining: 3.13s
42:	learn: 0.7224997	total: 1.32s	remaining: 1.75s
43:	learn: 0.7211035	total: 1.34s	remaining: 1.71s
23:	learn: 1.0497193	total: 1.34s	remaining: 9.83s
29:	learn: 0.7505989	total: 1.32s	remaining: 3.08s
16:	learn: 0.7982353	total: 1.33s	remaining: 6.5s
44:	learn: 0.7199202	total: 1.37s	remaining: 1.67s
22:	learn: 1.0513291	total: 1.34s	remaining: 10.3s
21:	learn: 1.0594604	total: 1.32s	remaining: 10.7s
33:	learn: 1.0128321	total: 1.35s	remaining: 6.58s
17:	learn: 1.0705063	total: 1.36s	remaining: 13.7s
22:	learn: 1.0556323	total: 1.33s	remaining: 10.3s
34:	learn: 1.0093010	total: 1.36s	remaining: 6.43s
45:	learn: 0.7189441	total: 1.39s	remaining: 1.63s
23:	learn: 1.0516904	total: 1.35s	remaining: 9.9s
35:	learn: 1.0059826	total: 1.38s	remaining: 6.28s
46:	learn: 0.7173139	total: 1.41s	remaining: 1.59s
30:	learn: 0.7478690	total: 1.38s	remaining: 3.08s
24:	learn: 1.0461151	total: 1.43s	remaining: 9.98s
47:	learn: 0.7160034	total: 1.43s	remaining: 1.55s
48:	learn: 0.7146657	total: 1.44s	remaining: 1.5s
25:	learn: 1.0421968	total: 1.45s	remaining: 9.69s
17:	learn: 0.7920672	total: 1.42s	remaining: 6.49s
49:	learn: 0.7134783	total: 1.46s	remaining: 1.46s
23:	learn: 1.0473767	total: 1.43s	remaining: 10.5s
18:	learn: 1.0665655	total: 1.44s	remaining: 13.7s
50:	learn: 0.7127364	total: 1.47s	remaining: 1.42s
31:	learn: 0.7458887	total: 1.45s	remaining: 3.07s
51:	learn: 0.7114190	total: 1.49s	remaining: 1.37s
26:	learn: 1.0383837	total: 1.49s	remaining: 9.56s
52:	learn: 0.7105507	total: 1.5s	remaining: 1.33s
53:	learn: 0.7098448	total: 1.51s	remaining: 1.29s
18:	learn: 0.7874461	total: 1.49s	remaining: 6.37s
27:	learn: 1.0345456	total: 1.52s	remaining: 9.36s
54:	learn: 0.7088210	total: 1.53s	remaining: 1.25s
19:	learn: 1.0624681	total: 1.51s	remaining: 13.6s
24:	learn: 1.0438102	total: 1.51s	remaining: 10.6s
32:	learn: 0.7435976	total: 1.5s	remaining: 3.06s
55:	learn: 0.7078192	total: 1.54s	remaining: 1.21s
56:	learn: 0.7068514	total: 1.55s	remaining: 1.17s
57:	learn: 0.7056017	total: 1.56s	remaining: 1.13s
58:	learn: 0.7046958	total: 1.57s	remaining: 1.09s
36:	learn: 1.0026454	total: 1.56s	remaining: 6.86s
59:	learn: 0.7036498	total: 1.58s	remaining: 1.05s
60:	learn: 0.7028521	total: 1.59s	remaining: 1.02s
37:	learn: 0.9993348	total: 1.57s	remaining: 6.7s
19:	learn: 0.7823757	total: 1.57s	remaining: 6.28s
33:	learn: 0.7411296	total: 1.57s	remaining: 3.04s
61:	learn: 0.7017648	total: 1.6s	remaining: 982ms
38:	learn: 0.9962335	total: 1.58s	remaining: 6.54s
24:	learn: 1.0480974	total: 1.56s	remaining: 11s
20:	learn: 1.0583677	total: 1.59s	remaining: 13.5s
62:	learn: 0.7010636	total: 1.62s	remaining: 950ms
39:	learn: 0.9931223	total: 1.6s	remaining: 6.39s
25:	learn: 1.0402691	total: 1.59s	remaining: 10.7s
40:	learn: 0.9901595	total: 1.61s	remaining: 6.25s
63:	learn: 0.7002406	total: 1.64s	remaining: 922ms
28:	learn: 1.0308074	total: 1.65s	remaining: 9.71s
64:	learn: 0.6995414	total: 1.67s	remaining: 899ms
20:	learn: 0.7783792	total: 1.64s	remaining: 6.17s
25:	learn: 1.0445059	total: 1.63s	remaining: 10.9s
21:	learn: 1.0544941	total: 1.66s	remaining: 13.4s
34:	learn: 0.7396408	total: 1.65s	remaining: 3.07s
65:	learn: 0.6981516	total: 1.7s	remaining: 873ms
66:	learn: 0.6974493	total: 1.71s	remaining: 843ms
22:	learn: 1.0508821	total: 1.69s	remaining: 13s
23:	learn: 1.0469584	total: 1.7s	remaining: 12.5s
35:	learn: 0.7376106	total: 1.69s	remaining: 3.01s
26:	learn: 1.0364979	total: 1.7s	remaining: 10.9s
26:	learn: 1.0406936	total: 1.68s	remaining: 10.8s
29:	learn: 1.0273382	total: 1.7s	remaining: 9.62s
67:	learn: 0.6964644	total: 1.73s	remaining: 816ms
21:	learn: 0.7746133	total: 1.72s	remaining: 6.09s
41:	learn: 0.9871161	total: 1.73s	remaining: 6.5s
24:	learn: 1.0433896	total: 1.73s	remaining: 12.1s
36:	learn: 0.7361401	total: 1.74s	remaining: 2.97s
68:	learn: 0.6958104	total: 1.78s	remaining: 801ms
27:	learn: 1.0328458	total: 1.77s	remaining: 10.9s
37:	learn: 0.7346021	total: 1.77s	remaining: 2.89s
69:	learn: 0.6952493	total: 1.81s	remaining: 777ms
38:	learn: 0.7329718	total: 1.78s	remaining: 2.78s
25:	learn: 1.0398140	total: 1.79s	remaining: 12s
39:	learn: 0.7315159	total: 1.78s	remaining: 2.68s
22:	learn: 0.7703218	total: 1.79s	remaining: 6s
30:	learn: 1.0237347	total: 1.79s	remaining: 9.78s
40:	learn: 0.7296364	total: 1.79s	remaining: 2.58s
42:	learn: 0.9842593	total: 1.82s	remaining: 6.65s
41:	learn: 0.7285217	total: 1.81s	remaining: 2.5s
70:	learn: 0.6942665	total: 1.85s	remaining: 757ms
43:	learn: 0.9813821	total: 1.83s	remaining: 6.5s
27:	learn: 1.0369819	total: 1.82s	remaining: 11.2s
42:	learn: 0.7271207	total: 1.83s	remaining: 2.43s
28:	learn: 1.0292254	total: 1.84s	remaining: 10.9s
44:	learn: 0.9784476	total: 1.85s	remaining: 6.37s
43:	learn: 0.7256449	total: 1.85s	remaining: 2.36s
23:	learn: 0.7660293	total: 1.86s	remaining: 5.9s
26:	learn: 1.0360151	total: 1.87s	remaining: 12s
71:	learn: 0.6935958	total: 1.91s	remaining: 744ms
44:	learn: 0.7242921	total: 1.88s	remaining: 2.3s
45:	learn: 0.7226770	total: 1.89s	remaining: 2.22s
31:	learn: 1.0202556	total: 1.89s	remaining: 9.93s
24:	learn: 0.7626403	total: 1.9s	remaining: 5.71s
46:	learn: 0.7215261	total: 1.91s	remaining: 2.15s
47:	learn: 0.7206202	total: 1.92s	remaining: 2.08s
25:	learn: 0.7598164	total: 1.92s	remaining: 5.46s
29:	learn: 1.0260074	total: 1.93s	remaining: 10.9s
28:	learn: 1.0332823	total: 1.92s	remaining: 11.3s
72:	learn: 0.6929474	total: 1.97s	remaining: 730ms
27:	learn: 1.0322898	total: 1.94s	remaining: 11.9s
48:	learn: 0.7191202	total: 1.94s	remaining: 2.02s
26:	learn: 0.7568010	total: 1.95s	remaining: 5.28s
49:	learn: 0.7181825	total: 1.96s	remaining: 1.96s
32:	learn: 1.0170992	total: 1.95s	remaining: 9.88s
50:	learn: 0.7169847	total: 1.97s	remaining: 1.89s
29:	learn: 1.0299587	total: 1.97s	remaining: 11.2s
51:	learn: 0.7160208	total: 1.99s	remaining: 1.84s
45:	learn: 0.9754615	total: 2.01s	remaining: 6.72s
30:	learn: 1.0225066	total: 2.01s	remaining: 11s
73:	learn: 0.6920783	total: 2.05s	remaining: 720ms
52:	learn: 0.7150182	total: 2.01s	remaining: 1.78s
28:	learn: 1.0286828	total: 2.03s	remaining: 11.9s
27:	learn: 0.7539947	total: 2.02s	remaining: 5.2s
53:	learn: 0.7137134	total: 2.03s	remaining: 1.73s
33:	learn: 1.0139088	total: 2.03s	remaining: 9.9s
54:	learn: 0.7122867	total: 2.05s	remaining: 1.67s
46:	learn: 0.9727222	total: 2.07s	remaining: 6.75s
31:	learn: 1.0192997	total: 2.07s	remaining: 10.9s
55:	learn: 0.7110762	total: 2.07s	remaining: 1.63s
74:	learn: 0.6914105	total: 2.12s	remaining: 706ms
29:	learn: 1.0253846	total: 2.09s	remaining: 11.8s
30:	learn: 1.0264967	total: 2.08s	remaining: 11.3s
28:	learn: 0.7517186	total: 2.09s	remaining: 5.11s
56:	learn: 0.7101903	total: 2.09s	remaining: 1.58s
34:	learn: 1.0107129	total: 2.1s	remaining: 9.9s
57:	learn: 0.7087439	total: 2.11s	remaining: 1.53s
75:	learn: 0.6905533	total: 2.16s	remaining: 682ms
58:	learn: 0.7079009	total: 2.13s	remaining: 1.48s
59:	learn: 0.7066406	total: 2.14s	remaining: 1.42s
60:	learn: 0.7056009	total: 2.15s	remaining: 1.37s
32:	learn: 1.0161538	total: 2.15s	remaining: 10.9s
61:	learn: 0.7045219	total: 2.15s	remaining: 1.32s
29:	learn: 0.7490783	total: 2.15s	remaining: 5.03s
30:	learn: 1.0218109	total: 2.17s	remaining: 11.8s
62:	learn: 0.7035314	total: 2.16s	remaining: 1.27s
47:	learn: 0.9698337	total: 2.18s	remaining: 6.91s
63:	learn: 0.7028835	total: 2.17s	remaining: 1.22s
31:	learn: 1.0232497	total: 2.17s	remaining: 11.4s
64:	learn: 0.7020016	total: 2.18s	remaining: 1.17s
65:	learn: 0.7011618	total: 2.19s	remaining: 1.13s
35:	learn: 1.0073574	total: 2.18s	remaining: 9.95s
33:	learn: 1.0130449	total: 2.21s	remaining: 10.8s
36:	learn: 1.0040132	total: 2.2s	remaining: 9.68s
37:	learn: 1.0006879	total: 2.21s	remaining: 9.43s
76:	learn: 0.6898332	total: 2.26s	remaining: 676ms
30:	learn: 0.7471964	total: 2.23s	remaining: 4.95s
31:	learn: 1.0185614	total: 2.24s	remaining: 11.8s
38:	learn: 0.9975289	total: 2.23s	remaining: 9.2s
66:	learn: 0.7001232	total: 2.24s	remaining: 1.1s
32:	learn: 1.0200801	total: 2.24s	remaining: 11.4s
39:	learn: 0.9944305	total: 2.24s	remaining: 8.97s
34:	learn: 1.0099471	total: 2.25s	remaining: 10.6s
40:	learn: 0.9915443	total: 2.26s	remaining: 8.77s
48:	learn: 0.9673694	total: 2.29s	remaining: 7.05s
33:	learn: 1.0168909	total: 2.27s	remaining: 11.1s
41:	learn: 0.9884938	total: 2.28s	remaining: 8.56s
67:	learn: 0.6991465	total: 2.29s	remaining: 1.08s
77:	learn: 0.6891890	total: 2.33s	remaining: 658ms
34:	learn: 1.0137493	total: 2.29s	remaining: 10.8s
42:	learn: 0.9856462	total: 2.29s	remaining: 8.37s
78:	learn: 0.6884155	total: 2.35s	remaining: 625ms
35:	learn: 1.0066515	total: 2.31s	remaining: 10.5s
43:	learn: 0.9828752	total: 2.31s	remaining: 8.18s
32:	learn: 1.0154075	total: 2.33s	remaining: 11.8s
31:	learn: 0.7455353	total: 2.32s	remaining: 4.93s
35:	learn: 1.0103915	total: 2.32s	remaining: 10.6s
36:	learn: 1.0070313	total: 2.33s	remaining: 10.3s
37:	learn: 1.0036739	total: 2.34s	remaining: 9.98s
49:	learn: 0.9646008	total: 2.37s	remaining: 7.1s
38:	learn: 1.0004728	total: 2.35s	remaining: 9.7s
79:	learn: 0.6877793	total: 2.4s	remaining: 601ms
39:	learn: 0.9973106	total: 2.36s	remaining: 9.45s
68:	learn: 0.6986184	total: 2.38s	remaining: 1.07s
36:	learn: 1.0034246	total: 2.38s	remaining: 10.5s
33:	learn: 1.0122882	total: 2.4s	remaining: 11.7s

In [26]:
for result in results:
    print(f"\nModel: {result['Model']}")
    print(f"Best Params: {result['Best Params']}")
    print(f"MSE: {result['MSE']:.4f}")
    print(f"MAE: {result['MAE']:.4f}")
    smape_val = result.get('SMAPE')
    if smape_val is not None:
        print(f"SMAPE: {smape_val:.2f}%")
    else:
        print("SMAPE: -")

Model: DecisionTree
Best Params: {'model__min_samples_split': 10, 'model__max_depth': 10}
MSE: 0.5398
MAE: 0.5255
SMAPE: 4.32%

Model: RandomForest
Best Params: {'model__n_estimators': 200, 'model__min_samples_split': 2, 'model__max_depth': None}
MSE: 0.4391
MAE: 0.4576
SMAPE: 3.77%

Model: CatBoost
Best Params: {'model__learning_rate': 0.1, 'model__iterations': 100, 'model__depth': 8}
MSE: 0.4859
MAE: 0.5022
SMAPE: 4.14%

Model: XGBoost
Best Params: {'model__n_estimators': 100, 'model__max_depth': 7, 'model__learning_rate': 0.1}
MSE: 0.4142
MAE: 0.4510
SMAPE: 3.72%

## for test data and submission

In [27]:
test.head()

      id      plate                 date  price
0  51636  P700TT790  2025-01-27 00:00:00    NaN
1  51637  M081TX797  2025-02-10 00:00:00    NaN
2  51638  T333HX777  2025-02-11 00:00:00    NaN
3  51639  H744BH977  2025-02-03 00:00:00    NaN
4  51640  X066EM777  2025-02-12 00:00:00    NaN

In [28]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7695 entries, 0 to 7694
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7695 non-null   int64
 1   plate   7695 non-null   object
 2   date    7695 non-null   object
 3   price   0 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 240.6+ KB

In [29]:
df_test = preprocessing_data(test)
df_test = df_test.drop(columns=['price'])
df_test = feature_engineering(df_test)

In [30]:
model = search.best_estimator_
model

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [31]:
predictions = model.predict(df_test)
predictions

array([11.711427, 11.660926, 12.504967, ..., 12.64084 , 11.809755,
       13.276496], shape=(7695,), dtype=float32)

In [35]:
submission = pd.DataFrame({
    'id': test['id'],
    'price': np.expm1(predictions)  # reversing the log transformation
})

submission.head()

      id          price
0  51636  121956.359375
1  51637  115950.335938
2  51638  269672.375000
3  51639  156077.687500
4  51640   87102.234375

In [36]:
submission.to_csv('submission.csv', index=False)